version: '3.8'

services:
  api:
    image: "api"
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - pg

  satellite:
    image: "satellite"
    build:
      context: ./satellite
    ports:
      - "5050:5050"

  mcs:
    image: "mcs"
    build: 
      context: ./mcs

  pg:
    image: postgres:14.3-alpine
    env_file: .env
    environment: 
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASS}
        POSTGRES_DB: ${PG_NAME}
        POSTGRES_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - type: bind
        source: ./db
        target: /app

  pgadmin:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PG_USER}@takehome.com
        PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports: 
        - "5001:80"
